language: ruby
cache: bundler
os: linux
dist: xenial
services:
  - docker

env:
  global:
    - "DOCKER_COMPOSE_VERSION=1.23.2"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssl

before_script:
  - docker build --no-cache -t vue .

# Si este script falla puede deberse a que se cambio la raiz o el nombre del proyecto en el dockerfile
script:
  - docker run --rm -it --name vue vue npm run test:unit;

after_script:
  - docker container stop vue
  - docker container rm vue
